language: python
install: true
#script: ./test.py
notifications:
  email: false

script:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x test.py
deploy:
  provider: script
  script: ls && UIEsearching/test.py
  skip_cleanup: true
